{"resource": "/insert/dollar", "path": "/insert/dollar", "httpMethod": "POST", "headers": "",
 "multiValueHeaders": "", "queryStringParameters": "", "multiValueQueryStringParameters": "",
 "pathParameters": "", "stageVariables": "",
 "requestContext": {"resourceId": "rk33sc", "resourcePath": "/insert/dollar", "httpMethod": "POST",
                    "extendedRequestId": "FNoNwFICCYcFsCA=", "requestTime": "05/Sep/2021:23:34:09 +0000",
                    "path": "/insert/dollar", "accountId": "636219084122", "protocol": "HTTP/1.1",
                    "stage": "test-invoke-stage", "domainPrefix": "testPrefix", "requestTimeEpoch": 1630884849421,
                    "requestId": "ba729573-cbea-4370-9115-10302eedc6b9",
                    "identity": {"cognitoIdentityPoolId": "", "cognitoIdentityId": "",
                                 "apiKey": "test-invoke-api-key", "principalOrgId": "",
                                 "cognitoAuthenticationType": "", "userArn": "arn:aws:iam::636219084122:root",
                                 "apiKeyId": "test-invoke-api-key-id",
                                 "userAgent": "aws-internal/3 aws-sdk-java/1.11.1030 Linux/5.4.129-72.229.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.302-b08 java/1.8.0_302 vendor/Oracle_Corporation cfg/retry-mode/legacy",
                                 "accountId": "636219084122", "caller": "636219084122",
                                 "sourceIp": "test-invoke-source-ip", "accessKey": "ASIAZIIM4ZVNGJZGQDMY",
                                 "cognitoAuthenticationProvider": "", "user": "636219084122"},
                    "domainName": "testPrefix.testDomainName", "apiId": "5ijkemiq04"}, "body": "",
 "isBase64Encoded": False}
