lambda_event = {
    "resource": "/",
    "path": "/",
    "httpMethod": "GET",
    "headers": None,
    "multiValueHeaders": None,
    "queryStringParameters": None,
    "multiValueQueryStringParameters": None,
    "pathParameters": None,
    "stageVariables": None,
    "requestContext": {
        "resourceId": "fake_id",
        "resourcePath": "/",
        "httpMethod": "GET",
        "extendedRequestId": "fake_extended_id",
        "requestTime": "05/Sep/2021:17:10:45 +0000",
        "path": "/",
        "accountId": "12345",
        "protocol": "HTTP/1.1",
        "stage": "test-invoke-stage",
        "domainPrefix": "testPrefix",
        "requestTimeEpoch": 1630861845803,
        "requestId": "5db60029-3d1e-44d8-ae71-111111111111",
        "identity": {
            "cognitoIdentityPoolId": None,
            "cognitoIdentityId": None,
            "apiKey": "test-invoke-api-key",
            "principalOrgId": None,
            "cognitoAuthenticationType": None,
            "userArn": "arn:aws:iam::123419081234:root",
            "apiKeyId": "test-invoke-api-key-id",
            "userAgent": "aws-internal/3 aws-sdk-java/1.11.1030 Linux/5.4.129-72.229.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.302-b08 java/1.8.0_302 vendor/Oracle_Corporation cfg/retry-mode/legacy",
            "accountId": "636219084122",
            "caller": "636219081234",
            "sourceIp": "test-invoke-source-ip",
            "accessKey": "ABCDEFGHIJKLGJZGQDMY",
            "cognitoAuthenticationProvider": None,
            "user": "123419081234"
        },
        "domainName": "testPrefix.testDomainName",
        "apiId": "1234123412"
    },
    "body": None,
    "isBase64Encoded": False
}
